### ISSUE TITLE
a improvement request

### ISSUE THREAD

**Issue by sqschrispaul** [CTCycle/EMADB-Autopilot#1]
An interesting project,Could you further navigate the 'Number of Individual Cases for a selected Reaction' page,  select the Reaction Groups and Reported Suspected Reaction on the right, And save the data.

**Comment by CTCycle** [comment]
Hello and thanks for your interest in my project! I was planning to get back to this repo and add new features, I will definitely take your suggestion into account. Hope to get to work on this as soon as possible, job duties are keeping me quite busy lately

**Comment by sqschrispaul** [comment]
> Hello and thanks for your interest in my project! I was planning to get back to this repo and add new features, I will definitely take your suggestion into account. Hope to get to work on this as soon as possible, job duties are keeping me quite busy lately

look forward to it

**Comment by CTCycle** [comment]
Just to be sure that I fully understood you concern, as the app downloads the complete dashboard (including the sheet you mentioned), do you wish to have a feature to download such info separately?

**Comment by CTCycle** [comment]
Hello, I've closed the issue since I did not get any update and the info you required is already present in the main dashboard. Should you like to get it as a separated feature, feel free to open a new issue thread!

CTCycle
